# python ArmReach_LLC_UitB.py --experiment_id depth_only_vision_no_adaptive --project_id myosuite_myouser_pointing --batch_size 128 --num_envs 1024 --num_minibatches 8 --vision_mode depth --adaptive_increase_success_rate 1.1 --adaptive_decrease_success_rate -0.1 --init_target_area_width_scale 1.0 --vision_output_size 128 --n_train_steps 50_000_000 --weights_reach 2.0 --weights_bonus 10.0 
# --reach_metric_coefficient 9.0

# python ArmReach_LLC_UitB.py --experiment_id depth_only_vision_no_adaptive_larger_network --project_id myosuite_myouser_pointing --batch_size 128 --num_envs 1024 --num_minibatches 8 --vision_mode depth --adaptive_increase_success_rate 1.1 --adaptive_decrease_success_rate -0.1 --init_target_area_width_scale 1.0 --vision_output_size 128 --n_train_steps 50_000_000 --weights_reach 2.0 --weights_bonus 10.0 --policy_hidden_layer_sizes 512 512 512 --value_hidden_layer_sizes 512 512 512

# python ArmReach_LLC_UitB.py --experiment_id depth_only_vision_bottlenecked_no_adaptive_higher_reach_bonus_and_penalty_higher__network_size_lower_reach_metric --project_id myosuite_myouser_pointing --batch_size 128 --num_envs 1024 --num_minibatches 8 --vision_mode depth --adaptive_increase_success_rate 1.1 --adaptive_decrease_success_rate -0.1 --init_target_area_width_scale 1.0 --vision_output_size 36 --n_train_steps 50_000_000 --weights_reach 2.0 --weights_bonus 10.0 --reach_metric_coefficient 5.0 --policy_hidden_layer_sizes 512 512 512 --value_hidden_layer_sizes 512 512 512

# python ArmReach_LLC_UitB.py --experiment_id depth_only_vision_bottlenecked_no_adaptive_higher_reach_bonus_and_penalty_higher__network_size_higher_ec --project_id myosuite_myouser_pointing --batch_size 128 --num_envs 1024 --num_minibatches 8 --vision_mode depth --adaptive_increase_success_rate 1.1 --adaptive_decrease_success_rate -0.1 --init_target_area_width_scale 1.0 --vision_output_size 36 --n_train_steps 50_000_000 --weights_reach 2.0 --weights_bonus 10.0 --reach_metric_coefficient 9.0 --policy_hidden_layer_sizes 512 512 512 --value_hidden_layer_sizes 512 512 512 --entropy_cost 5e-3

# python ArmReach_LLC_UitB.py --experiment_id depth_only_vision_bottlenecked_no_adaptive_higher_reach_bonus_and_penalty_higher__network_size_super_high_ec --project_id myosuite_myouser_pointing --batch_size 128 --num_envs 1024 --num_minibatches 8 --vision_mode depth --adaptive_increase_success_rate 1.1 --adaptive_decrease_success_rate -0.1 --init_target_area_width_scale 1.0 --vision_output_size 36 --n_train_steps 50_000_000 --weights_reach 2.0 --weights_bonus 10.0 --reach_metric_coefficient 9.0 --policy_hidden_layer_sizes 512 512 512 --value_hidden_layer_sizes 512 512 512 --entropy_cost 1e-2

# python ArmReach_LLC_UitB.py --experiment_id depth_only_vision_bottlenecked_no_adaptive_higher_reach_bonus_and_penalty_higher__network_size_original_reach_metric --project_id myosuite_myouser_pointing --batch_size 128 --num_envs 1024 --num_minibatches 8 --vision_mode depth --adaptive_increase_success_rate 1.1 --adaptive_decrease_success_rate -0.1 --init_target_area_width_scale 1.0 --vision_output_size 36 --n_train_steps 50_000_000 --weights_reach 2.0 --weights_bonus 10.0 --reach_metric_coefficient 10.0 --policy_hidden_layer_sizes 512 512 512 --value_hidden_layer_sizes 512 512 512

# python ArmReach_LLC_UitB.py --experiment_id depth_only_vision_bottlenecked_no_adaptive_higher_network_size --project_id myosuite_myouser_pointing --batch_size 128 --num_envs 1024 --num_minibatches 8 --vision_mode depth --adaptive_increase_success_rate 1.1 --adaptive_decrease_success_rate -0.1 --init_target_area_width_scale 1.0 --vision_output_size 36 --n_train_steps 50_000_000 --policy_hidden_layer_sizes 512 512 512 --value_hidden_layer_sizes 512 512 512